main:main.c Global Catalog Json Serializer
	gcc main.c -o test -g
Global:Global.h
	gcc Global.h -c
Catalog:Catalog.h Catalog.c
	gcc Catalog.h Catalog.c -c
Json:Json.h Json.c
	gcc Json.h Json.c -c
Serializer:Serializer.h Serializer.c
	gcc Serializer.h Serializer.c -c
clean:
	rm -f test *.c~ *.h~ *.o *.h.gch
